# generated by datamodel-codegen:
#   filename:  author.json
#   timestamp: 2026-05-19T15:03:10+00:00

from __future__ import annotations
from pydantic import Field
from schemas.base_resource import BaseResourceSchema


class AuthorSchema(BaseResourceSchema):
    name: str = Field(..., description="Name of the author")
    books: str = Field(..., description="URL to filtered books collection")
