# generated by datamodel-codegen:
#   filename:  book.json
#   timestamp: 2026-05-06T14:51:53+00:00

from __future__ import annotations
from datetime import date
from pydantic import Field
from src.util.schemas import BaseResourceSchema, RelatedResource


class BookSchema(BaseResourceSchema):
    title: str
    isbn: str
    published_date: date | None = None
    description: str | None = None
    language: str | None = None
    page_count: int
    rating: float = Field(..., ge=0.0, le=5.0)
    voters: int = Field(..., ge=0)
    authors: list[RelatedResource] = Field(
        ..., description="The author(s) of the book."
    )
    publisher: RelatedResource = Field(..., description="The publisher.")
    categories: list[RelatedResource] | None = Field(
        None, description="The categories the book belongs to."
    )
