stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - rpi
  script:
    - echo "Deploying to production..."
    - docker compose -f docker-compose.prod.yml up -d --build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'  # Only run on main branch
