# https://gitlab.lnu.se/1dv027/content/examples/restfulgo/-/blob/main/.gitlab-ci.yml

.before_script_ssh_setup: &before_script_ssh_setup
  # Ensure ssh-agent is installed and started, essential for managing SSH keys.
  # (Change apt-get to yum if using an RPM-based image)
  # debug to see what env variables we have
  - env | grep REMOTE

  - command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )

  # Start the ssh-agent in the background.
  - eval $(ssh-agent -s)


  # Add the SSH private key stored in the SSH_PRIVATE_KEY variable to the ssh-agent.
  # Using 'tr' to remove carriage return characters for compatibility with ed25519 keys.
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  # Create the .ssh directory and set the correct permissions.
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  # Add the remote server's SSH key to the known_hosts file. see: https://docs.gitlab.com/ci/jobs/ssh_keys/#verifying-the-ssh-host-keys
  - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/known_hosts
  - cat ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  # testing
  - docker context use default
  # - echo $DOCKER_HOST
  - docker context ls


image: docker:29-cli

stages:
  - deploy

# Job to deploy to the production environment.
deploy_production_job:
  stage: deploy
  environment:
    name: production
    url: http://$REMOTE_HOST
  variables:
    REMOTE_HOST: $REMOTE_HOST       # Set the REMOTE_HOST variable for production.
    DOCKER_HOST: ssh://$REMOTE_USER@$REMOTE_HOST  # Docker connection via SSH.
    API_HOST: "rest_api"
  before_script: *before_script_ssh_setup  # Reuse SSH setup steps.
  script:
    - echo "Deploying to production..."
    # lets see if this works instead
    - docker compose -f docker-compose.prod.yml up -d --build
    # - docker -H ssh://$REMOTE_USER@$REMOTE_HOST compose -f docker-compose.yaml up --build -d
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'  # Only run on main branch
