services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    secrets:
      - db_user
      - db_password
      - db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/db_user) -d $$(cat /run/secrets/db_name)"]
      interval: 5s
      timeout: 5s
      retries: 5

  setup:
    build:
      context: .
      dockerfile: setup/dockerfile
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CSV_PATH: data/google-books-subset.csv
      CHUNK_SIZE: 5000
    secrets:
      - db_name
      - db_user
      - db_password
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./setup/data-subset:/app/data
    restart: "no"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      FLASK_SECRET_KEY_FILE: /run/secrets/flask_secret_key
      JWT_PRIVATE_KEY_FILE: /run/secrets/jwt_private_key
      JWT_PUBLIC_KEY_FILE: /run/secrets/jwt_public_key
    secrets:
      - db_name
      - db_user
      - db_password
      - flask_secret_key
      - jwt_private_key
      - jwt_public_key
    depends_on:
      db:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

secrets:
  db_name:
    file: ./secrets/db_name.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  flask_secret_key:
    file: ./secrets/flask_secret_key.txt
  jwt_private_key:
    file: ./secrets/bibliocat-api-jwt-key
  jwt_public_key:
    file: ./secrets/bibliocat-api-jwt-key.pub

volumes:
  postgres_data:
