# generated by datamodel-codegen:
#   filename:  reading_log.json
#   timestamp: 2026-05-20T13:50:08+00:00

from __future__ import annotations
from datetime import date, datetime
from pydantic import Field
from src.util.schemas.base_resource import BaseResourceSchema


class ReadingLogSchema(BaseResourceSchema):
    started_at: date | datetime = Field(
        ..., description="The date and time for when the reading started"
    )
    ended_at: date | datetime | None = Field(
        ..., description="The date and time for when the reading ended"
    )
