FROM python:3.12-alpine3.22

COPY --from=ghcr.io/astral-sh/uv:0.10.5 /uv /uvx /bin/

WORKDIR /app

COPY setup/uv.lock setup/pyproject.toml ./

# Sync dependencies
RUN uv sync --frozen --no-dev

# Copy the src directory and main.py
COPY setup/src ./src
COPY setup/main.py .

# Copy models from api directory
COPY api/src/util/models/ ./src/models/

# Set PYTHONPATH to include /app
ENV PYTHONPATH=/app

CMD ["/app/.venv/bin/python", "main.py"]
