FROM python:3.12-alpine3.22

COPY --from=ghcr.io/astral-sh/uv:0.10.5 /uv /uvx /bin/

WORKDIR /app

COPY api/uv.lock api/pyproject.toml ./

RUN apk add --no-cache curl

RUN uv sync --frozen --no-dev

COPY api/src ./src
COPY api/static ./static

CMD ["sh", "-c", "/app/.venv/bin/gunicorn --bind 0.0.0.0:5000 --workers 2 src.main:app"]
