name: Container retention policy

on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *"  # 06:30 UTC every day

jobs:
  clean:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    name: Delete old images
    steps:
      - name: Container Retention Policy
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.PAT }}
          image-names: "bibliocat-api*"
          image-tags: "!latest"            # Don't target latest images
          cut-off: 60min
          dry-run: true
